apiVersion: v2
name: beproeving
description: The right place for first time implementations and learning
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  # helm repo add eso https://charts.external-secrets.io
  - name: external-secrets
    repository: "@eso"
    version: 1.1.0
    condition: external-secrets-operator.enabled