{{- if .Values.kiss.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: adapter-secret
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "podiumd.name" . }}-adapter-secret
stringData:
  CLIENTS__0__ID: {{ .Values.kiss.adapter.clientId | quote }}
  CLIENTS__0__SECRET: {{ .Values.kiss.adapter.secret | quote }}
  ESUITE_CLIENT_ID: {{ .Values.kiss.adapter.esuite.clientId | quote }}
  ESUITE_CLIENT_SECRET: {{ .Values.kiss.adapter.esuite.secret | quote }}
  SMOELENBOEK_TOKEN: {{ .Values.kiss.settings.syncJobs.medewerkers.token | quote }}
{{- end }}
