apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    {{- include "podiumd.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "podiumd.name" . }}-frontend-config
data:
  AFDELINGEN_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.objecten.baseUrl | quote }}
  AFDELINGEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.kiss.objecttypen.baseUrlExtern .Values.kiss.objecttypen.afdelingUUID | quote }}
  CONTACTMOMENTEN_BASE_URL: {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.adapter.baseUrl | quote }}
  ELASTIC_BASE_URL: {{ default (printf "https://kiss-es-http.%s.svc.cluster.local:9200" .Release.Namespace) .Values.kiss.elastic.baseUrl | quote }}
  {{- if .Values.kiss.email.host }}
  EMAIL_HOST: {{ .Values.kiss.email.host | quote }}
  {{- end }}
  {{- if .Values.kiss.email.port }}
  EMAIL_PORT:  {{ .Values.kiss.email.port }}
  {{- end }}
  ENTERPRISE_SEARCH_BASE_URL: {{ default (printf "https://kiss-ent-http.%s.svc.cluster.local:3002" .Release.Namespace) .Values.kiss.enterpriseSearch.baseUrl | quote }}
  {{- if .Values.kiss.email.enableSSL }}
  EMAIL_ENABLE_SSL: {{ .Values.kiss.email.enableSSL }}
  {{- end }}
  {{- if .Values.kiss.email.feedbackFrom }}
  FEEDBACK_EMAIL_FROM: {{ .Values.kiss.email.feedbackFrom | quote }}
  {{- end }}
  {{- if .Values.kiss.email.feedbackTo }}
  FEEDBACK_EMAIL_TO:  {{ .Values.kiss.email.feedbackTo | quote }}
  {{- end }}
  GROEPEN_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.objecten.baseUrl | quote }}
  GROEPEN_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" .Values.kiss.objecttypen.baseUrlExtern .Values.kiss.objecttypen.groepUUID | quote }}
  HAAL_CENTRAAL_BASE_URL: {{ .Values.kiss.brp.baseUrl | quote }}
  INTERNE_TAAK_BASE_URL: {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.adapter.baseUrl | quote }}
  INTERNE_TAAK_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" (default (printf "http://objecttypen.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.objecttypen.baseUrlIntern) .Values.kiss.objecttypen.interneTaakUUID | quote }}
  KLANTEN_BASE_URL: {{ printf "%s/klanten" (default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.adapter.baseUrl) | quote }}
  KVK_BASE_URL: {{ .Values.kiss.kvk.baseUrl | quote }}
  MEDEWERKER_OBJECTEN_BASE_URL:  {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.adapter.baseUrl | quote }}
  MEDEWERKER_OBJECTTYPES_BASE_URL: {{ .Values.kiss.objecttypen.baseUrlExtern | quote }}
  OIDC_AUTHORITY: {{ .Values.kiss.oidc.authority | quote }}
  OIDC_MEDEWERKER_IDENTIFICATIE_CLAIM: {{ .Values.kiss.oidc.medewerkerIdentificatieClaim | quote }}
  {{- if .Values.kiss.oidc.medewerkerIdentificatieTruncate }}
  OIDC_MEDEWERKER_IDENTIFICATIE_TRUNCATE: {{ .Values.kiss.oidc.medewerkerIdentificatieTruncate }}
  {{- end }}
  ORGANISATIE_IDS: {{ .Values.kiss.organisatieIds | quote }}
  POSTGRES_DB: {{ .Values.kiss.database.name | quote }}
  POSTGRES_HOST: {{ .Values.kiss.database.host | quote }}
  SDG_OBJECT_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.objecten.baseUrl | quote }}
  SDG_OBJECT_TYPE_URL: {{ printf "%s/api/v2/objecttypes/%s" (default (printf "http://objecttypen.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.objecttypen.baseUrlIntern) .Values.kiss.objecttypen.kennisartikelUUID | quote }}
  USE_VACS: {{ .Values.kiss.vac.useVacs | quote }}
  VAC_OBJECTEN_BASE_URL: {{ default (printf "http://objecten.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.vac.objectenBaseUrl | quote }}
  VAC_OBJECT_TYPE_URL: {{ .Values.kiss.vac.objectTypeUrl | quote }}
  VAC_OBJECT_TYPE_VERSION: {{ .Values.kiss.vac.objectTypeVersion | quote }}
  ZAAKSYSTEEM_DEEPLINK_PROPERTY: "identificatie"
  ZAAKSYSTEEM_DEEPLINK_URL: {{ printf "%s/mp/zaak/" .Values.kiss.esuite.baseUrl | quote }}
  ZAKEN_BASE_URL:  {{ default (printf "http://kiss-adapter.%s.svc.cluster.local" .Release.Namespace) .Values.kiss.adapter.baseUrl | quote }}
